config/routes.rb
Rails.application.routes.draw do
  mount UserImpersonate::Engine => '/impersonate', as: 'impersonate_engine'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#home'
  
  resources :dashboard, only: [:index]
  resources :donations, only: [:new, :edit, :create, :update]
  resources :withdrawals, only: [:new, :create]
  resources :payment_accounts
  resources :money_transactions, only: [:index, :edit, :update]
  resources :tools
  resources :wallets, only: [:show]
  resources :adverts, only: [:index, :edit, :update, :new, :create]
  devise_for :users
  resources :announcements

  match '/wallets/add/' => 'wallets#add_to_wallet', via: :post, as: 'add_to_wallet'
  match '/wallets/add_bonus/' => 'wallets#add_bonus_to_wallet', via: :post, as: 'add_bonus_to_wallet'
  match '/wallets/withdraw/' => 'wallets#withdraw_from_wallet', via: :post, as: 'withdraw_from_wallet'
  match '/wallets/fund/' => 'wallets#fund_wallet', via: :put, as: 'fund_wallet'
 
  match '/money_transactions/toggle_transaction_status/:id' => 'money_transactions#toggle_transaction_status', as: 'toggle_transaction_status', via: :post
 
  match '/donations/:user_id' => 'donations#user_donations', as: 'user_donations', via: :get
 
  match '/withdrawals/:user_id' => 'withdrawals#user_withdrawals', as: 'user_withdrawals', via: :get
 
  match 'welcome/how_to' => 'welcome#how_to', as: 'how_to_donate', via: :get
  match 'welcome/faq' => 'welcome#faq', as: 'faq', via: :get
  match 'welcome/terms' => 'welcome#terms', as: 'terms', via: :get
 
  match '/dashboard/admin' => 'dashboard#admin', as: 'dashboard_admin', via: :get
  match '/dashboard/testing' => 'dashboard#testing', as: 'testing', via: :get
  match '/dashboard/money_transactions' => 'dashboard#money_transactions', as: 'all_transactions', via: :get
  match 'dashboard/filter_money_transactions' => 'dashboard#filter_money_transactions', as: 'filter_money_transactions', via: :post

  match '/adverts/toggle_advert_status/:id' => 'adverts#toggle_advert_status', as: 'toggle_advert_status', via: :post
  match '/adverts/user_ads' => 'adverts#user_ads', as: 'user_ads', via: :get


  namespace :api do
    namespace :v1 do
      resources :donations, only: [:index, :create, :destroy, :update]
      resources :withdrawals, only: [:index, :create, :destroy, :update]
    end
  end
  

end

app/controllers/api/v1/dashboard_controller.rb
class Api::V1::DashboardController < Api::V1::BaseController
  before_action :authenticate_user!
  
  def index
    if current_user.is?('admin')
      @money_transactions = MoneyTransaction.where(status: 3)
      render 'dashboard/admin'
    else
      render 'dashboard/index'
    end
  end
  
  def money_transactions
    @all_transactions = MoneyTransaction.all
  end
  
  def profile
    @payment_account = current_user.bank_account
  end
  
  def admin
  end
  
  def testing
    @donations = current_user.donations
    @withdrawals = current_user.withdrawals
  end

  def filter_money_transactions
    f = filter_params
    @all_transactions = MoneyTransaction.where("created_at >= '#{(Time.parse(f[:from]))}' AND created_at <= '#{(Time.parse(f[:to]))}'")
    render 'dashboard/money_transactions'
  end
  
  private
  
  def filter_params
    params.require(:transaction_filter).permit(:from, :to)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if current_user.is?('admin')
      @money_transactions = MoneyTransaction.where(status: 3)
      @adverts = Advert.all
      render 'dashboard/admin'
    else
      render 'dashboard/index'
    end
  end
  
  def money_transactions
    @all_transactions = MoneyTransaction.all
    @unmatched_donations = Donation.unmatched
    @unmatched_withdrawals = Withdrawal.unmatched
  end
  
  def users
    @active_users = User.active_users
    @inactive_users = User.inactive_users
  end
  
  def profile
    @payment_account = current_user.bank_account
  end
  
  def admin
    @money_transactions = MoneyTransaction.where(status: 3)
    @adverts = Advert.all
    render 'dashboard/admin'
  end
  
  def testing
    @donations = current_user.donations
    @withdrawals = current_user.withdrawals
  end

  def filter_money_transactions
    f = filter_params
    if Time.valid_date_string?(f[:from]) && Time.valid_date_string?(f[:to])
      @all_transactions = MoneyTransaction.where("created_at >= '#{(Time.parse(f[:from]))}' AND created_at <= '#{(Time.parse(f[:to]))}'")
    else
      @all_transactions = MoneyTransaction.all
    end
    render 'dashboard/money_transactions'
  end
  
  private
  
  def filter_params
    params.permit(:from, :to)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def unpaid_transactions_total(money_transactions)
    return nil unless money_transactions.present?
    sum = 0
    money_transactions.each{ |mt| sum += mt.amount }
    number_to_currency(sum, unit: 'R', precision: 2)
  end
end

app/views/dashboard/admin.html.erb
<div id="fh5co-pricing-section" >
  <div class="container" >
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
        <h2 style = "font-size: 50px; color: #FFFFFF" >UNPAID DONATIONS</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-md-offset-1 text-center animate-box">
        <div class="pricing">
          <div class="col-md-10 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2 class="pricing-plan"> UNPAID DONATIONS </h2>
              <h2 class="price"> <%= unpaid_transactions_total(@money_transactions) %> </h2>
              <table style="overflow-x:auto;">
                <tr>
                  <th>Date</th>
                  <th>Reporter</th>
                  <th>Donor</th>
                  <th>Amount</th>
                  <th>Re-assign</th>
                  <th>Remove</th>
                </tr>
                <% if @money_transactions.present? %>
                  <% @money_transactions.each do |mt| %>
                    <tr>
                      <td class="pricing-plan"> <%= mt.updated_at.strftime('%F') %> </td>
                      <td class="pricing-plan"> <%= mt.withdrawal.user.first_name %> </td>
                      <td class="pricing-plan"> <%= mt.donation.user.first_name %> </td>
                      <td class="pricing-plan"><%= mt.amount %> </td>
                      <td><%= form_tag(toggle_transaction_status_path(mt.id)) do %>
                            <%= hidden_field_tag(:status, MoneyTransaction.statuses[:pending]) %>
                            <%= submit_tag 'Re-assign',
                                           class: 'btn btn-primary btn-outline',
                                           data: { confirm: 'Are you sure?' }
                            %>
                        <% end %>
                      </td>
                      <td>
                        <%= form_tag(toggle_transaction_status_path(mt.id)) do %>
                            <%= hidden_field_tag(:status, MoneyTransaction.statuses[:blocked]) %>
                            <%= submit_tag 'Remove Donation',
                                           class: 'btn btn-primary btn-outline',
                                           data: { confirm: 'Are you sure?' }
                            %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>


<div id="fh5co-pricing-section" >
  <div class="container" >
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
        <h2 style = "font-size: 50px; color: #FFFFFF" >ADVERT ADMIN </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center animate-box">
        <div class="pricing">
          <div class="col-md-12 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2> MANAGE ADVERTS </h2>
              <table style="overflow-x:auto;">
                <tr>
                  <th>Posted On</th>
                  <th>Content</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Address</th>
                  <th>Status</th>
                  <th></th>
                </tr>
                <% if @adverts.present? %>
                    <% @adverts.each do |ad| %>
                        <tr>
                          <td class="pricing-plan"> <%= ad.created_at.strftime('%F') %> </td>
                          <td class="pricing-plan"><%= ad.advert_body %> </td>
                          <td class="pricing-plan"><%= ad.phone %> </td>
                          <td class="pricing-plan"><%= ad.email %> </td>
                          <td class="pricing-plan"><%= ad.address %> </td>
                          <td class="pricing-plan"> <%= ad.status %> </td>
                          <td>
                            <%= form_tag(toggle_advert_status_path(ad.id)) do %>
                                <%= hidden_field_tag(:id, ad.id) %>
                                <%= hidden_field_tag(:status, Advert.statuses[:published]) %>
                                <%= submit_tag 'Approve',
                                               class: 'btn btn-primary btn-outline',
                                               data: { confirm: 'You are about to approve this ad, are you sure?' },
                                               disabled: !ad.requested?
                                %>
                            <% end %>
                          </td>
                          <td>
                            <%= form_tag(toggle_advert_status_path(ad.id)) do %>
                                <%= hidden_field_tag(:id, ad.id) %>
                                <%= hidden_field_tag(:status, Advert.statuses[:rejected]) %>
                                <%= submit_tag 'Decline',
                                               class: 'btn btn-primary btn-outline',
                                               data: { confirm: 'You are about to decline this ad, are you sure?' },
                                               disabled: !ad.requested?
                                %>
                            <% end %>
                          </td>
                        </tr>
                    <% end %>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </div>
</div>

app/views/dashboard/announcement_center.html.erb
<div id="fh5co-pricing-section" class="fh5co-light-grey-section">
  <div id="fh5co-pricing-section" >
    <div class="container" >
      <div class="row">
        <div class="col-md-12 col-md-offset-0 text-center animate-box">
          <div class="pricing">
            <div class="col-md-12 animate-box">
              <div class="price-box" style="overflow-x:auto;">
                <h2 class="pricing"> NEWS FEEDS UPDATE </h2>
                <table style="overflow-x:auto;">
                  <tr>
                    <th>MESSAGE</th>
                    <th>UPDATE</th>
                  </tr>
                  <tr>
                    <td class="pricing-plan">
                      <%= form_tag(announcements_path) do %>
                          <%= text_area_tag(:content) %>
                        <td colspan="2"><%= submit_tag 'POST', class: 'btn btn-primary btn-outline' %></td>
                    <% end %>
                  </tr>
                  <% if @announcements.present? %>
                    <% @announcements.each do |a| %>
                      <tr>
                        <td><%= a.content %></td>
                        <td><%= link_to 'Destroy',
                                        announcement_path(a.id),
                                        class: 'btn btn-primary btn-outline',
                                        method: :delete,
                                        data: {confirm: 'Are you sure?'} %>
                        </td>
                      </tr>
                    <% end %>
                  <% end %>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container" >
      <div class="row">
        <div class="col-md-12 col-md-offset-0 text-center animate-box">
          <div class="pricing">
            <div class="col-md-12 animate-box">
              <div class="price-box" style="overflow-x:auto;">
                <h2 class="pricing"> SLIDER UPLOADS </h2>
                <table style="overflow-x:auto;">
                  <tr>
                    <th>ATTACH</th>
                    <th>VIEW SLIDER</th>
                    <th>UPLOAD</th>
                  </tr>
                  <tr>
                    <td class="overflow">
                      <input class="btn btn-custom" type="file" id="myFile">
                    </td>
                    <td class="pricing-plan"> Mlindisi </td>
                    <td><a href="#" class="btn btn-primary btn-outline">UPLOAD</a></td>
                  </tr>
                  <tr>
                    <td class="overflow">
                      <input class="btn btn-custom" type="file" id="myFile">
                    </td>
                    <td class="pricing-plan"> Mlindisi </td>
                    <td><a href="#" class="btn btn-primary btn-outline">UPLOAD</a></td>
                  </tr>
                  <tr>
                    <td class="overflow">
                      <input class="btn btn-custom" type="file" id="myFile">
                    </td>
                    <td class="pricing-plan"> Mlindisi </td>
                    <td><a href="#" class="btn btn-primary btn-outline">UPLOAD</a></td>
                  </tr>

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/money_transactions.html.erb
<div id="fh5co-pricing-section" >
  <div class="container" >
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center animate-box">
        <div class="pricing">
          <div class="col-md-12 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2 class="pricing-plan"> MONTHLY TRANSACTIONS </h2>
              <h2 class="price"> <%= MoneyTransaction.total %></h2>
              <table style="overflow-x:auto;" id="transactions-table">
                <%= form_tag(filter_money_transactions_path) do %>
                    FROM: <%= text_field_tag(:from,'' ,placeholder: 'dd/mm/yyyy') %>
                    TO: <%= text_field_tag(:to, '',placeholder: 'dd/mm/yyyy') %>
                    <%= submit_tag 'Filter', class: 'btn btn-primary btn-outline' %>
                <% end %>
                <tr>
                  <th onclick="sortTable(0, 'transactions-table')">Date</th>
                  <th onclick="sortTable(1, 'transactions-table')">Receiver</th>
                  <th onclick="sortTable(2, 'transactions-table')">Donor</th>
                  <th onclick="sortTable(3, 'transactions-table')">Amount</th>
                  <th onclick="sortTable(4, 'transactions-table')">Status</th>
                </tr>
                <% if @all_transactions.present? %>
                  <% @all_transactions.each do |trx| %>
                    <tr>
                      <td class="pricing-plan"> <%= trx.created_at.strftime('%F') %> </td>
                      <td class="pricing-plan"><%= trx.withdrawal_user_name %> </td>
                      <td class="pricing-plan"> <%= trx.donation_user_name %> </td>
                      <td class="pricing-plan"> <%= display_as_money(trx.amount) %></td>
                      <td class="pricing-plan"> <%= trx.status %> </td>
                    </tr>
                 <% end %>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
     </div>



      <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
          <h2 style="font-size: 50px; color: #FFFFFF"> Pending Donations </h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-md-offset-0 text-center animate-box">
          <div class="pricing">
            <div class="col-md-12 animate-box">
              <div class="price-box" style="overflow-x:auto;">
                <h2 class="pricing-plan"> Unmatched Donations Balance Total:  <%= display_as_money(Donation.unmatched_total) %></h2>
                <% if @unmatched_donations.present? %>
                    <table>
                      <thead>
                      <th>Created Date</th>
                      <th>Amount</th>
                      <th>Balance</th>
                      <th>User</th>
                      </thead>
                      <tbody>
                      <% @unmatched_donations.each do |donation| %>
                          <tr>
                            <td><%= donation.created_at.strftime('%d/%m/%Y') %></td>
                            <td><%= display_as_money(donation.amount) %></td>
                            <td><%= display_as_money(donation.balance) %></td>
                            <td><%= donation.user.name %></td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                <% else %>
                    <h3>There are no pending donations</h3>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
          <h2 style="font-size: 50px; color: #FFFFFF"> Pending Withdrawals </h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-md-offset-0 text-center animate-box">
          <div class="pricing">
            <div class="col-md-12 animate-box">
              <div class="price-box" style="overflow-x:auto;">
                <h2 class="pricing-plan"> Unmatched Withdrawals Balance Total:  <%= display_as_money(Withdrawal.unmatched_total) %></h2>
                <% if @unmatched_withdrawals.present? %>
                    <table>
                      <thead>
                      <th>Created Date</th>
                      <th>Amount</th>
                      <th>Balance</th>
                      <th>User</th>
                      </thead>
                      <tbody>
                      <% @unmatched_withdrawals.each do |withdrawal| %>
                          <tr>
                            <td><%= withdrawal.created_at.strftime('%d/%m/%Y') %></td>
                            <td><%= display_as_money(withdrawal.amount) %></td>
                            <td><%= display_as_money(withdrawal.balance) %></td>
                            <td><%= withdrawal.user.name %></td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                <% else %>
                    <h3>There are no pending donations</h3>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/dashboard/testing.html.erb
<div id="fh5co-pricing-section" >
  <div class="container" >
    <div class="row">
      <div class="col-md-10 col-md-offset-2 text-center fh5co-heading animate-box">
        <h2 style = "font-size: 50px; color: #FFFFFF" >Testing</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-md-offset-2 text-center animate-box">
        <div class="pricing">
          <div class="col-md-10 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2 class="pricing-plan"> MY DONATIONS </h2>
              <h2 class="price"> <%= @donations.count %> </h2>
              <% if @donations.present? %>
                  <table>
                    <thead>
                    <th>Created Date</th>
                    <th>Expiry Date</th>
                    <th>Profit from date</th>
                    <th>Amount</th>
                    <th>Months<br>Invested</th>
                    <th>Profit</th>
                    <th></th>
                    </thead>
                    <tbody>
                    <% @donations.each do |donation| %>
                        <tr>
                          <td><%= donation.created_at.strftime('%d %b %Y') %></td>
                          <td><%= (donation.maturity_date).strftime('%d %b %Y') %></td>
                          <td><%= (donation.profit_from_date).strftime('%d %b %Y') %></td>
                          <td><%= display_as_money(donation.amount) %></td>
                          <td><%= donation.months_invested %></td>
                          <td><%= display_as_money(donation.profit) %></td>
                          <td>
                            <%= link_to 'Edit', edit_donation_path(donation.id) %>
                          </td>
                        </tr>
                    <% end %>
                    </tbody>
                  </table>
              <% else %>
                  <h3>You have no active donations</h3>
                  <button type="submit" name="submit" class="btn btn-primary btn-outline"
                          style="" required="required" data-toggle="modal" data-target="#Deposit">Donate
                  </button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/users.html.erb
<div id="fh5co-pricing-section">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
        <h2 style="font-size: 50px; color: #FFFFFF"> Active Users </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center animate-box">
        <div class="pricing">
          <div class="col-md-12 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2> <%= @active_users.count %> Active Users </h2>
              <% if @active_users.present? %>
                  <input type="text" id="myInput" onkeyup="searchTable('myInput', 'active-users-table')" placeholder="Search for user email..">
                  <table id="active-users-table">
                    <thead>
                    <th onclick="sortTable(0, 'active-users-table')">Registration Date</th>
                    <th onclick="sortTable(1, 'active-users-table')">Name</th>
                    <th onclick="sortTable(2, 'active-users-table')">Email</th>
                    <th onclick="sortTable(3, 'active-users-table')">Cellphone</th>
                    <th onclick="sortTable(4, 'active-users-table')">Referrals</th>
                    <th onclick="sortTable(5, 'active-users-table')">Donations</th>
                    </thead>
                    <tbody>
                    <% @active_users.each do |user| %>
                        <tr>
                          <td><%= user.created_at.strftime('%F') %></td>
                          <td><%= user.name %></td>
                          <td><%= user.email %></td>
                          <td><%= user.cellphone %></td>
                          <td><%= user.referees.count %></td>
                          <td><%= display_as_money(user.donation_total) %></td>
                        </tr>
                    <% end %>
                    </tbody>
                  </table>
              <% end %>
            </div>

            <div class="price-box" style="overflow-x:auto;">
              <h2> <%= @inactive_users.count %> Inactive Users </h2>
              <% if @inactive_users.present? %>
                  <input type="text" id="myInput2" onkeyup="searchTable('myInput2', 'inactive-users-table')" placeholder="Search for user email..">
                  <table id="inactive-users-table">
                    <thead>
                    <th onclick="sortTable(0, 'inactive-users-table')">Registration Date</th>
                    <th onclick="sortTable(1, 'inactive-users-table')">Name</th>
                    <th onclick="sortTable(2, 'inactive-users-table')">Email</th>
                    <th onclick="sortTable(3, 'inactive-users-table')">Cellphone</th>
                    <th onclick="sortTable(4, 'inactive-users-table')">Referrals</th>
                    <th onclick="sortTable(5, 'inactive-users-table')">Donations</th>
                    </thead>
                    <tbody>
                    <% @inactive_users.each do |user| %>
                        <tr>
                          <td><%= user.created_at.strftime('%F') %></td>
                          <td><%= user.name %></td>
                          <td><%= user.email %></td>
                          <td><%= user.cellphone %></td>
                          <td><%= user.referees.count %></td>
                          <td><%= display_as_money(user.donation_total) %></td>
                        </tr>
                    <% end %>
                    </tbody>
                  </table>
              <% end %>
            </div>

            <div class="row">
              <div class="col-md-12 col-md-offset-0 text-center animate-box">
                <div class="pricing">
                  <div class="col-md-12 animate-box">
                    <div class="price-box" style="overflow-x:auto;">
                      <h2> Fund Wallet </h2>
                      <table>
                        <%= form_tag(fund_wallet_path, method: :put) do %>
                            <tr>
                              <th class="pricing-plan">Email</th>
                                <td><%= text_field_tag(:email, nil) %></td>
                            </tr>
                            <tr>
                              <th class="pricing-plan">Amount</th>
                              <td><%= number_field_tag(:amount) %></td>
                            </tr>
                            <tr>
                              <td colspan="2"><%= submit_tag 'Fund' %></td>
                            </tr>
                        <% end %>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>