config/routes.rb
Rails.application.routes.draw do
  mount UserImpersonate::Engine => '/impersonate', as: 'impersonate_engine'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#home'
  
  resources :dashboard, only: [:index]
  resources :donations, only: [:new, :edit, :create, :update]
  resources :withdrawals, only: [:new, :create]
  resources :payment_accounts
  resources :money_transactions, only: [:index, :edit, :update]
  resources :tools
  resources :wallets, only: [:show]
  resources :adverts, only: [:index, :edit, :update, :new, :create]
  devise_for :users
  resources :announcements

  match '/wallets/add/' => 'wallets#add_to_wallet', via: :post, as: 'add_to_wallet'
  match '/wallets/add_bonus/' => 'wallets#add_bonus_to_wallet', via: :post, as: 'add_bonus_to_wallet'
  match '/wallets/withdraw/' => 'wallets#withdraw_from_wallet', via: :post, as: 'withdraw_from_wallet'
  match '/wallets/fund/' => 'wallets#fund_wallet', via: :put, as: 'fund_wallet'
 
  match '/money_transactions/toggle_transaction_status/:id' => 'money_transactions#toggle_transaction_status', as: 'toggle_transaction_status', via: :post
 
  match '/donations/:user_id' => 'donations#user_donations', as: 'user_donations', via: :get
 
  match '/withdrawals/:user_id' => 'withdrawals#user_withdrawals', as: 'user_withdrawals', via: :get
 
  match 'welcome/how_to' => 'welcome#how_to', as: 'how_to_donate', via: :get
  match 'welcome/faq' => 'welcome#faq', as: 'faq', via: :get
  match 'welcome/terms' => 'welcome#terms', as: 'terms', via: :get
 
  match '/dashboard/admin' => 'dashboard#admin', as: 'dashboard_admin', via: :get
  match '/dashboard/testing' => 'dashboard#testing', as: 'testing', via: :get
  match '/dashboard/money_transactions' => 'dashboard#money_transactions', as: 'all_transactions', via: :get
  match 'dashboard/filter_money_transactions' => 'dashboard#filter_money_transactions', as: 'filter_money_transactions', via: :post

  match '/adverts/toggle_advert_status/:id' => 'adverts#toggle_advert_status', as: 'toggle_advert_status', via: :post
  match '/adverts/user_ads' => 'adverts#user_ads', as: 'user_ads', via: :get


  namespace :api do
    namespace :v1 do
      resources :donations, only: [:index, :create, :destroy, :update]
      resources :withdrawals, only: [:index, :create, :destroy, :update]
    end
  end
  

end

app/controllers/api/v1/money_transactions_controller.rb
class Api::V1::MoneyTransactionsController < Api::V1::BaseController
  before_action :authenticate_user!
  
  def index
    @donations = current_user.non_compounded_donations
    @withdrawals = current_user.pending_withdrawals
  end
  
  def toggle_transaction_status
    mt = MoneyTransaction.find(params[:id])
    mt.update!(status: params[:status].to_i)
    redirect_to money_transactions_path, flash[:notice] => 'Transaction Updated'
  end
end

app/controllers/money_transactions_controller.rb
class MoneyTransactionsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @donations = current_user.non_compounded_donations
    @withdrawals = current_user.pending_withdrawals
  end
  
  def edit
    @money_transaction = MoneyTransaction.find(params[:id])
  end
  
  def update
    @money_transaction = MoneyTransaction.find(params[:id])
    if @money_transaction.update!(update_params)
      redirect_to money_transactions_path
    else
      render 'edit'
    end
  end
  
  def toggle_transaction_status
    mt = MoneyTransaction.find(params[:id])
    mt.update!(status: params[:status].to_i)
    if current_user.is?('admin')
      redirect_to dashboard_admin_path, flash[:notice] => 'Transaction Updated'
    else
      redirect_to money_transactions_path, flash[:notice] => 'Transaction Updated'
    end
    
  end
  
  private
  
  def update_params
    params.require(:money_transaction).permit(:proof_of_payment)
  end
end

app/views/money_transactions/edit.html.erb
<div>
  <div id="fh5co-pricing-section" >
    <div class="container" >
      <div class="row">
        <div class="col-md-12 col-md-offset-3 text-center animate-box">
          <div class="pricing">
            <div class="col-md-8 animate-box">
              <div class="price-box">
                <h2 class="pricing-plan"><%= image_tag('deposit.png', :alt => 'Community Wealth SA 2017') %></h2>
                <%= form_for(@money_transaction, multipart: true) do |mt| %>
                    <h2> UPLOAD PROOF </h2>
                    <center>
                      <div class="price">
                        <%= mt.file_field(:proof_of_payment, { class: 'btn btn-primary btn-outline', required: true }) %>
                      </div>
                    </center>
                    <%= submit_tag 'Upload', class: 'btn btn-primary btn-outline', required: 'required', data: { toggle: 'modal', target: '#deposit' }%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/money_transactions/index.html.erb
<div id="fh5co-pricing-section">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
        <h2 style="font-size: 50px; color: #FFFFFF"> My Transactions </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center animate-box">
        <div class="pricing">
          <div class="col-md-12 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2 class="pricing-plan"> Transactions on Donation </h2>
              <% if @donations.present? %>
                  <% @donations.each_with_index do |donation, index| %>
                      <br>
                      <h4>Donation <%= index + 1 %>: Amount:
                        <%= display_as_money(donation.amount) %>
                        Balance: <%= display_as_money(donation.balance) %>
                        <br>
                        <hr>
                      </h4>
                      <% if donation.money_transactions.present? %>
                          <table>
                            <thead>
                            <th></th>
                            <th>Recipient Name</th>
                            <th>Contact</th>
                            <th>Bank Name</th>
                            <th>Account Number</th>
                            <th>Branch Code</th>
                            <th>Account Type</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Upload Proof</th>
                            </thead>
                            <tbody>
                            <% donation.money_transactions.each_with_index do |tr, index| %>
                                <tr>
                                  <td><%= index + 1 %></td>
                                  <td><%= tr.withdrawal_user_name %></td>
                                  <td><%= tr.withdrawal_user_contact %></td>
                                  <td><%= tr.recipient_bank_name %></td>
                                  <td><%= tr.recipient_account_number %></td>
                                  <td><%= tr.recipient_branch_code %></td>
                                  <td><%= tr.recipient_account_type %></td>
                                  <td><%= tr.amount %></td>
                                  <td><%= tr.status %></td>
                                  <td>
                                    <% if tr.proof_of_payment.thumb.url.present? %>
                                      <%= image_tag(tr.proof_of_payment.thumb.url)  %>
                                    <% else %>
                                      <%= link_to 'Upload', edit_money_transaction_path(tr.id), class: 'btn btn-primary btn-outline' %>
                                    <% end %>
                                  </td>
                                </tr>
                            <% end %>
                            </tbody>
                          </table>
                      <% end %>
                  <% end %>
              <% else %>
                  <h3>You have no active donation transactions</h3>
              <% end %>
            </div>

            <div class="price-box" style="overflow-x:auto;">
              <h2 class="pricing-plan"> Transactions on Withdrawal </h2>
              <% if @withdrawals.present? %>
                  <% @withdrawals.each_with_index do |withdrawal, index| %>
                      <br>
                      <h4>Withdrawal <%= index + 1 %>:
                        Amount: <%= display_as_money(withdrawal.amount) %>
                        Balance: <%= display_as_money(withdrawal.balance) %>
                      </h4>
                      <hr>
                      <br>
                      <% if withdrawal.pending_money_transactions.present? %>
                          <table>
                            <thead>
                            <th></th>
                            <th>Donor Name</th>
                            <th>Contact</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Hours Elapsed</th>
                            <th>Proof of payment</th>
                            <th colspan="2">Complete/Reject</th>
                            </thead>
                            <tbody>
                            <% withdrawal.pending_money_transactions.each_with_index do |tr, index| %>
                                <tr>
                                  <td><%= index + 1 %></td>
                                  <td><%= tr.donation_user_name %></td>
                                  <td><%= tr.donation_user_contact %></td>
                                  <td><%= display_as_money(tr.amount) %></td>
                                  <td><%= tr.status %></td>
                                  <td><%= tr.hours_elapsed %></td>
                                  <td>
                                    <% if tr.proof_of_payment.present? %>
                                        <%= image_tag tr.proof_of_payment.thumb.url %>
                                    <% else %>
                                      NOT YET UPLOADED
                                    <% end %>
                                  </td>
                                  <td>
                                    <%= form_tag(toggle_transaction_status_path(tr.id)) do %>
                                        <%= hidden_field_tag(:id, current_user.id) %>
                                        <%= hidden_field_tag(:status, MoneyTransaction.statuses[:completed]) %>
                                        <%= submit_tag 'Complete',
                                                       class: 'btn btn-primary btn-outline',
                                                       data: { confirm: 'Are you sure?' },
                                                       disabled: !tr.pending?
                                        %>
                                    <% end %>
                                  </td>
                                  <td>
                                    <%= form_tag(toggle_transaction_status_path(tr.id)) do %>
                                      <%= hidden_field_tag(:id, current_user.id) %>
                                      <%= hidden_field_tag(:status, MoneyTransaction.statuses[:rejected]) %>
                                      <%= submit_tag 'Reject',
                                                     class: 'btn btn-primary btn-outline',
                                                     data: { confirm: 'Are you sure?' },
                                                     disabled: !tr.pending? || tr.hours_elapsed < 48
                                      %>
                                    <% end %>
                                  </td>
                                </tr>
                            <% end %>
                            </tbody>
                          </table>
                      <% end %>
                  <% end %>
              <% else %>
                  <h3>You have no active Withdrawal transactions</h3>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="fh5co-counters" style="background-image: url(<%= image_path('2.jpg') %>);" data-stellar-background-ratio="0.5" id="counter-animate">
    <div class="fh5co-narrow-content animate-box">
      <div class="row" >
        <div class="col-md-10">
            <div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
                <div class="fh5co-icon">
                  <i class="icon-info"></i>
                </div>
              <div class="fh5co-text">
                 <h2 style = "color: #da1212"> ACTIVE TRANSACTIONS </h2><br/>
                  <p style = "color: #fff"> All active transactions will show on this screen. Whether you are donationg to a participant or receiving donation. When donating or receiving, you will see all users that you must connect with here. </p>
              </div>
            </div> 
        </div>
      </div>
    </div>
</div>