config/routes.rb
Rails.application.routes.draw do
  mount UserImpersonate::Engine => '/impersonate', as: 'impersonate_engine'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#home'
  
  resources :dashboard, only: [:index]
  resources :donations, only: [:new, :edit, :create, :update]
  resources :withdrawals, only: [:new, :create]
  resources :payment_accounts
  resources :money_transactions, only: [:index, :edit, :update]
  resources :tools
  resources :wallets, only: [:show]
  resources :adverts, only: [:index, :edit, :update, :new, :create]
  devise_for :users
  resources :announcements

  match '/wallets/add/' => 'wallets#add_to_wallet', via: :post, as: 'add_to_wallet'
  match '/wallets/add_bonus/' => 'wallets#add_bonus_to_wallet', via: :post, as: 'add_bonus_to_wallet'
  match '/wallets/withdraw/' => 'wallets#withdraw_from_wallet', via: :post, as: 'withdraw_from_wallet'
  match '/wallets/fund/' => 'wallets#fund_wallet', via: :put, as: 'fund_wallet'
 
  match '/money_transactions/toggle_transaction_status/:id' => 'money_transactions#toggle_transaction_status', as: 'toggle_transaction_status', via: :post
 
  match '/donations/:user_id' => 'donations#user_donations', as: 'user_donations', via: :get
 
  match '/withdrawals/:user_id' => 'withdrawals#user_withdrawals', as: 'user_withdrawals', via: :get
 
  match 'welcome/how_to' => 'welcome#how_to', as: 'how_to_donate', via: :get
  match 'welcome/faq' => 'welcome#faq', as: 'faq', via: :get
  match 'welcome/terms' => 'welcome#terms', as: 'terms', via: :get
 
  match '/dashboard/admin' => 'dashboard#admin', as: 'dashboard_admin', via: :get
  match '/dashboard/testing' => 'dashboard#testing', as: 'testing', via: :get
  match '/dashboard/money_transactions' => 'dashboard#money_transactions', as: 'all_transactions', via: :get
  match 'dashboard/filter_money_transactions' => 'dashboard#filter_money_transactions', as: 'filter_money_transactions', via: :post

  match '/adverts/toggle_advert_status/:id' => 'adverts#toggle_advert_status', as: 'toggle_advert_status', via: :post
  match '/adverts/user_ads' => 'adverts#user_ads', as: 'user_ads', via: :get


  namespace :api do
    namespace :v1 do
      resources :donations, only: [:index, :create, :destroy, :update]
      resources :withdrawals, only: [:index, :create, :destroy, :update]
    end
  end
  

end

app/models/withdrawal.rb
# == Schema Information
#
# Table name: money_requests
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  type             :text
#  amount           :decimal(17, 4)
#  balance          :decimal(17, 4)
#  status           :integer          default("pending"), not null
#  maturity_date    :date
#  matured          :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  compounded       :boolean          default(FALSE)
#  profit_from_date :datetime
#  donation_id      :integer
#

class Withdrawal < MoneyRequest
  validates :user_id, presence: true
  validates :amount, presence: true
  validates_numericality_of :amount, greater_than: 0
  validate :payment_details_provided

  belongs_to :user
  has_many :money_transactions

  after_commit on: [:create] do
    make_money_transactions
  end

  def make_money_transactions
    return unless self.requires_transaction
    MoneyTransactionService.new(self).match_with_donations
  end
  
  def pending_money_transactions
    self.money_transactions.where(status: [MoneyTransaction.statuses[:pending], MoneyTransaction.statuses[:rejected]])
  end
  
  def payment_details_provided
    if user.payment_account.blank? || user.payment_account.account_number.blank?
      errors.add(:payment_account, 'required for withdrawal')
    end
  end

  def self.unmatched
    Withdrawal.where('balance > 0 and status = 1').to_a
  end
  
  def self.unmatched_total
    Withdrawal.unmatched.map(&:balance).sum
  end
end

app/controllers/api/v1/withdrawals_controller.rb
class Api::V1::WithdrawalsController < Api::V1::BaseController
  before_action :authenticate_user!

  def new
    @withdrawal = Withdrawal.new
  end

  def create
    respond_to do |format|
      withdrawal = MoneyRequestService.new(withdrawals_params, {type: Withdrawal.name }).call
      
      if withdrawal.save!
        current_user.wallet.update!(balance: (current_user.wallet.balance - withdrawal.amount))
        format.js { render inline: 'location.reload();' }
        format.html { redirect_to dashboard_index_path, flash[:notice] => 'withdrawal Request Successful' }
      else
        format.js { render inline: 'location.reload();' }
        format.html { render 'new' }
      end
    
    end
  end

  def user_withdrawals
    @withdrawals = Withdrawal.order(:created_at).where(user_id: params[:user_id])
  end


  private

  def withdrawals_params
    params.permit(:user_id, :amount)
  end
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/withdrawals/new.html.erb
<h1>New Withdrawal Request</h1>
<%= form_for (@withdrawal) do |f| %>
    <% flash.each do |key, value| %>
        <p class="flash <%= key %>"><%= value %></p>
    <% end %>
    <h2>Wallet Amount: R <%= current_user.wallet.amount %></h2>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <p><%= f.label :amount %>: <%= f.number_field(:amount) %></p>
  </div>
  <div class="field">
    <p><%= f.submit %></p>
  </div>
<% end %>

app/views/withdrawals/user_withdrawals.html.erb
<div id="fh5co-pricing-section">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
        <h2 style="font-size: 50px; color: #FFFFFF"> Withdrawal History </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center animate-box">
        <div class="pricing">
          <div class="col-md-12 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2 class="pricing-plan"> Active withdrawal </h2>
              <% if @withdrawals.present? %>
                  <table>
                    <thead>
                    <th>Created Date</th>
                    <th>Amount</th>
                    <th>Balance</th>
                    <th>Status</th>
                    </thead>
                    <tbody>
                    <% @withdrawals.each do |withdrawal| %>
                        <tr>
                          <td><%= withdrawal.created_at.strftime('%d/%m/%Y') %></td>
                          <td><%= display_as_money(withdrawal.amount) %></td>
                          <td><%= display_as_money(withdrawal.balance) %></td>
                          <td><%= withdrawal.status %></td>
                        </tr>
                    <% end %>
                    </tbody>
                  </table>
              <% else %>
                  <h3>You have no active withdrawals</h3>
                  <h4>Wallet Balance: <%= display_as_money(current_user.wallet.amount) %></h4>
                  <%= link_to 'Withdraw', withdraw_from_wallet_path, class: 'btn btn-primary btn-outline', via: :post %>
              <% end %>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="fh5co-counters" style="background-image: url(<%= image_path('2.jpg') %>);" data-stellar-background-ratio="0.5" id="counter-animate">
      <div class="fh5co-narrow-content animate-box">
        <div class="row" >
          <div class="col-md-10">
              <div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
                  <div class="fh5co-icon">
                    <i class="icon-info"></i>
                  </div>
                <div class="fh5co-text">
                   <h2 style = "color: #da1212"> WITHDRAWAL HISTORY </h2><br/>
                    <p style = "color: #fff"> All withdrawals are being kept on record per user. This page will display the history of withdrawals. The current balance will also be displayed as Wallet Balance. </p>
                </div>
              </div> 
          </div>
        </div>
      </div>
  </div>