config/routes.rb
Rails.application.routes.draw do
  mount UserImpersonate::Engine => '/impersonate', as: 'impersonate_engine'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#home'
  
  resources :dashboard, only: [:index]
  resources :donations, only: [:new, :edit, :create, :update]
  resources :withdrawals, only: [:new, :create]
  resources :payment_accounts
  resources :money_transactions, only: [:index, :edit, :update]
  resources :tools
  resources :wallets, only: [:show]
  resources :adverts, only: [:index, :edit, :update, :new, :create]
  devise_for :users
  resources :announcements

  match '/wallets/add/' => 'wallets#add_to_wallet', via: :post, as: 'add_to_wallet'
  match '/wallets/add_bonus/' => 'wallets#add_bonus_to_wallet', via: :post, as: 'add_bonus_to_wallet'
  match '/wallets/withdraw/' => 'wallets#withdraw_from_wallet', via: :post, as: 'withdraw_from_wallet'
  match '/wallets/fund/' => 'wallets#fund_wallet', via: :put, as: 'fund_wallet'
 
  match '/money_transactions/toggle_transaction_status/:id' => 'money_transactions#toggle_transaction_status', as: 'toggle_transaction_status', via: :post
 
  match '/donations/:user_id' => 'donations#user_donations', as: 'user_donations', via: :get
 
  match '/withdrawals/:user_id' => 'withdrawals#user_withdrawals', as: 'user_withdrawals', via: :get
 
  match 'welcome/how_to' => 'welcome#how_to', as: 'how_to_donate', via: :get
  match 'welcome/faq' => 'welcome#faq', as: 'faq', via: :get
  match 'welcome/terms' => 'welcome#terms', as: 'terms', via: :get
 
  match '/dashboard/admin' => 'dashboard#admin', as: 'dashboard_admin', via: :get
  match '/dashboard/testing' => 'dashboard#testing', as: 'testing', via: :get
  match '/dashboard/money_transactions' => 'dashboard#money_transactions', as: 'all_transactions', via: :get
  match 'dashboard/filter_money_transactions' => 'dashboard#filter_money_transactions', as: 'filter_money_transactions', via: :post

  match '/adverts/toggle_advert_status/:id' => 'adverts#toggle_advert_status', as: 'toggle_advert_status', via: :post
  match '/adverts/user_ads' => 'adverts#user_ads', as: 'user_ads', via: :get


  namespace :api do
    namespace :v1 do
      resources :donations, only: [:index, :create, :destroy, :update]
      resources :withdrawals, only: [:index, :create, :destroy, :update]
    end
  end
  

end

app/models/advert.rb
# == Schema Information
#
# Table name: adverts
#
#  id          :integer          not null, primary key
#  title       :text
#  image_url   :text
#  advert_body :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  status      :integer          default("requested"), not null
#  user_id     :integer          not null
#  phone       :text
#  email       :text
#  address     :text
#

class Advert < ApplicationRecord
  enum status: { requested: 1, published: 2, rejected: 3 }

  def requested?
    Advert.statuses[self.status] == Advert.statuses[:requested]
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update]
  
  def index
    if current_user && current_user.is?('admin')
      @adverts = Advert.all
      render 'adverts/admin_ads'
    elsif current_user && current_user.is?('user')
      render 'user_ads'
    end
    @adverts = Advert.where(status: Advert.statuses[:published])
  end
  
  def edit
    @advert = Advert.find(params[:id])
  end
  
  def update
    ad = Advert.find(params[:id])
    respond_to do |format|
      if ad.update!(advert_params)
        format.js { render inline: 'location.reload();' }
        format.html { redirect_to adverts_path }
      end
    end
  end
  
  def create
    ad = Advert.create(advert_params)
    respond_to do |format|
      if ad.save
        format.js { render inline: 'location.reload();' }
        format.html { redirect_to user_donations_path(user_id: current_user.id) }
      end
    end
  end
  
  def destroy
    ad = Advert.find(params[:id])
    ad.destroy!
    redirect_to adverts_path
  end
  
  def toggle_advert_status
    ad = Advert.find(params[:id])
    ad.update!(status: params[:status].to_i)
    redirect_to dashboard_admin_path
  end
  
  private

  def advert_params_js
    params.permit(:user_id, :title, :advert_body, :phone, :address, :email)
  end
  
  def advert_params
    params.require(:advert).permit(:user_id, :title, :advert_body, :phone, :address, :email, :status)
  end
end

app/controllers/api/v1/adverts_controller.rb
class Api::V1::AdvertsController < Api::V1::BaseController
  before_action :authenticate_user!, only: [:create]
  def create
    
  end
  
  
  private
  def adverts_params
    params.permit()
  end
end

app/views/adverts/_ads_container.html.erb
<div id="fh5co-pricing-section" class="fh5co-light-grey-section ">
  <% if adverts.present? %>
      <% adverts.each do |ad| %>
          <%= render partial: 'advert', locals: {
              advert: ad
          } %>
      <% end %>
  <% else %>
    <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
      <h2 style="font-size: 25px; color: #FFFFFF">Your advert could be here! Advertise with us.
        <%= link_to 'SIGN UP', new_user_registration_path %> or <%= link_to 'SIGN IN', user_session_path %></h2>
    </div>
  <% end %>
</div>

app/views/adverts/_advert.html.erb
<div class="col-md-4 animate-box">
  <div class="price-box">
    <h2 class="pricing-plan"><%= advert.title %></h2>
    <p class="show-read-more"><%= advert.advert_body %></p>
    <div>
      <p>Email: <%= advert.email %></p>
      <p>Phone: <%= advert.phone %></p>
      <div class="address">
        <%= advert.address %>
      </div>
    </div>
  </div>
</div>

app/views/adverts/admin_ads.html.erb
<div id="fh5co-pricing-section">
  <div class="container" >
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center animate-box">
        <div class="pricing">
          <div class="col-md-12 animate-box">
            <div class="price-box" style="overflow-x:auto;">
              <h2> MANAGE ADVERTS </h2>
              <table style="overflow-x:auto;">
                <tr>
                  <th>Posted On</th>
                  <th>Content</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Address</th>
                  <th>Status</th>
                  <th></th>
                </tr>
                <% if @adverts.present? %>
                    <% @adverts.each do |ad| %>
                        <tr>
                          <td class="pricing-plan"> <%= ad.created_at.strftime('%F') %> </td>
                          <td class="pricing-plan"><%= ad.advert_body %> </td>
                          <td class="pricing-plan"><%= ad.phone %> </td>
                          <td class="pricing-plan"><%= ad.email %> </td>
                          <td class="pricing-plan"><%= ad.address %> </td>
                          <td class="pricing-plan"> <%= ad.status %> </td>
                          <td><%= link_to 'Delete', advert_path(ad.id), method: :delete ,
                                          data: { confirm: 'You are about to delete this ad, are you sure?' }%>
                          </td>
                          <td><%= link_to 'Edit', edit_advert_path(ad.id)%></td>
                        </tr>
                    <% end %>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/adverts/edit.html.erb
<div id="fh5co-pricing-section">
  <div class="container">
    <div class="row">
      <div id="fh5co-pricing-section">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-md-offset-3 text-center animate-box">
              <div class="pricing">
                <div class="col-md-8 animate-box">
                  <div class="price-box">
                    <h2 class="pricing-plan">PLEASE ENTER YOUR AD DETAILS HERE</h2>
                    <table>
                      <%= form_for(@advert) do |ad| %>
                          <%= hidden_field_tag(:user_id, current_user.id) %>
                          <tr>
                            <th class="pricing-plan">Advert Title</th>
                            <td colspan="2"><%= ad.text_field(:title, class: 'btn btn-primary btn-outline', colspan: 2) %></td>
                          </tr>
                          <tr>
                            <th class="pricing-plan">Phone</th>
                            <td><%= ad.text_field(:phone, class: 'btn btn-primary btn-outline') %></td>
                          </tr>
                          <tr>
                            <th class="pricing-plan">Email</th>
                            <td><%= ad.text_field(:email, class: 'btn btn-primary btn-outline') %></td>
                          </tr>
                          <tr>
                            <th class="pricing-plan">Advert Text</th>
                            <td colspan="2"><%= ad.text_area(:advert_body) %></td>
                          </tr>
                          <tr>
                            <th class="pricing-plan">City</th>
                            <td colspan="2"><%= ad.text_field(:address) %></td>
                          </tr>
                          <% if current_user.is?('admin') %>
                              <tr>
                                <th class="pricing-plan">Status</th>
                                <td colspan="2"><%= ad.select(:status, %w(requested published rejected)) %></td>
                              </tr>
                          <% end %>
                          <tr>
                            <td colspan="2" align="center">
                              <%= ad.submit 'Submit', class: 'btn btn-primary btn-outline' %>
                            </td>
                          </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/adverts/index.html.erb
<div id="fh5co-pricing-section" class="fh5co-light-grey-section ">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
          <h2 style="font-size: 50px; color: #FFFFFF"> FREE BUSINESS MARKETING </h2>
        </div>

        <%= render partial: 'ads_container', locals: {
            adverts: @adverts
        } %>
      </div>
    </div>
</div>

app/views/adverts/user_ads.html.erb
<div id="fh5co-pricing-section">
<div class="container" >
  <div class="row">
    <div class="col-md-12 col-md-offset-2 text-center animate-box">
      <div class="pricing">
        <div class="col-md-10 animate-box">
          <div class="price-box" style="overflow-x:auto;">
            <h2 class="pricing-plan"> MY ADVERTS </h2>
            <h2 class="price"><%= current_user.adverts.count %> <%= 'Ad'.pluralize(current_user.adverts.count) %> Posted</h2>
            <table style="overflow-x:auto;">
              <tr>
                <th>Posted On</th>
                <th>Content</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
                <th>Status</th>
              </tr>
              <% if current_user.adverts.present? %>
                  <% current_user.adverts.each do |ad| %>
                      <tr>
                        <td class="pricing-plan"> <%= ad.created_at.strftime('%F') %> </td>
                        <td class="pricing-plan"><%= ad.advert_body %> </td>
                        <td class="pricing-plan"><%= ad.phone %> </td>
                        <td class="pricing-plan"><%= ad.email %> </td>
                        <td class="pricing-plan"><%= ad.address %> </td>
                        <td class="pricing-plan"> <%= ad.status %> </td>
                        <td><%= link_to 'Edit', edit_advert_path(ad.id) %></td>
                      </tr>
                  <% end %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>